sudo: false
dist: xenial
language: python
python:
 - "2.7"
env:
 - PROF=deb9
addons:
  apt:
    packages:
    - openssl
    - openjdk-8-jdk-headless
install:
  - pip install -r requirements-${PROF}.txt
script:
  - ./test.sh
