name: setuptools-dso

on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ${{ matrix.python-version }}
    strategy:
      fail-fast: true
      matrix:
        python-version: [2.7, 3.5, 3.6, 3.7, 3.8, 3.9, 3.x]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Builder Info
        run: |
          set -x
          which python
          python --version
          python -m pip --version

      - name: Test
        shell: bash
        run: |
          set -x
          pip install -r requirements.txt
          ./test.sh
